### ISSUE TITLE
Zinc time on Windows

### ISSUE THREAD

**Issue by noahverney** [austin-j-taylor/Invested#1]
Keybind for zinc time on Windows? Also, controller doesn't work for me. I connected the controller, but can't seem to get it to  work on this

**Comment by artemos-git** [comment]
Keybind for zinc is Tab. With a gamepad, it's toggled by clicking in the left joystick. This will change in the next version.
For the controller, you have to go to Settings > Gameplay > Control Scheme and change it to gamepad. It only works with Xbox controllers.

**Comment by noahverney** [comment]
ok thanks
